import type { FileDefinitions } from 'vsc-icon-maker';

export const files: FileDefinitions = {
  'angular': { name: ['angular.json', '.angulardoc.json'] },
  'audio': { ext: ['mp3', 'ogg', 'wav'] },
  'bun': { name: ['bun.lockb'] },
  'c': { langId: ['c'] },
  'changelog': { name: ['changelog', 'changelog.md', 'changelog.txt'] },
  'coffee-script': { langId: ['coffeescript'] },
  'compact': {
    ext: [
      '7z',
      'AppImage',
      'aur',
      'bz2',
      'deb',
      'ear',
      'exe',
      'flatpak',
      'gz',
      'iso',
      'jar',
      'obs',
      'pkg',
      'ppa',
      'rar',
      'rpm',
      'snap',
      'tar',
      'tgz',
      'vsix',
      'war',
      'xz',
      'zip',
      'zst',
    ],
    langId: ['code-text-binary'],
  },
  'config': {
    langId: ['ini', 'makefile', 'ignore', 'editorconfig'],
  },
  'cpp': { langId: ['cpp', 'cuda-cpp'] },
  'cs': { ext: ['cs'], langId: ['csharp'] },
  'csproj': { ext: ['csproj'] },
  'css': { langId: ['css'] },
  'dart': { langId: ['dart'] },
  'diagram': {
    ext: ['dio', 'drawio', 'drawio.png', 'drawio.svg', 'uml'],
    langId: ['drawio'],
  },
  'diff': { langId: ['diff'] },
  'docker-compose': { langId: ['dockercompose'] },
  'docker-ignore': { ext: ['dockerignore'] },
  'docker': { langId: ['dockerfile'] },
  'document': {
    ext: [
      'doc',
      'docm',
      'docx',
      'dot',
      'dotm',
      'dotx',
      'gdoc',
      'odt',
      'ott',
      'pages',
    ],
  },
  'env': { ext: ['env', 'venv'], langId: ['dotenv'] },
  'flutter': { ext: ['flutter-plugins', 'packages'] },
  'git': {
    ext: ['gitignore', 'gitattributes', 'gitkeep'],
    langId: ['git-commit', 'git-rebase'],
  },
  'go': { langId: ['go'] },
  'gradle': {
    ext: ['gradle'],
    name: ['gradlew', 'gradlew.bat', 'gradlew.sh'],
    langId: ['gradle-kotlin-dsl'],
  },
  'html': { langId: ['html'] },
  'http': { ext: ['bru', 'http', 'rc', 'rest', 'web'] },
  'image': {
    ext: [
      'avif',
      'bmp',
      'gif',
      'heic',
      'heif',
      'icns',
      'ico',
      'jpeg',
      'jpg',
      'png',
      'tiff',
      'webp',
    ],
  },
  'java-class': { ext: ['class', 'jmod'] },
  'java': { ext: ['java', 'jsp'], langId: ['java'] },
  'js-config': { ext: ['config.js', 'config.cjs', 'config.mjs'] },
  'js-map': { ext: ['js.map', 'cjs.map', 'mjs.map'] },
  'js-test': {
    ext: [
      'jest.js',
      'jest.cjs',
      'jest.mjs',
      'spec.js',
      'spec.cjs',
      'spec.mjs',
      'test.js',
      'test.cjs',
      'test.mjs',
    ],
  },
  'js': { langId: ['javascript'] },
  'jsconfig': { name: ['jsconfig.json'] },
  'json': { ext: ['map'], langId: ['json', 'jsonc', 'jsonl'] },
  'julia': { langId: ['julia', 'juliamarkdown'] },
  'latex': { langId: ['latex', 'tex'] },
  'license': { name: ['license', 'license.md', 'license.txt'] },
  'lock': { ext: ['lock'] },
  'log': { langId: ['log'] },
  'lua': { langId: ['lua'] },
  'manifest': { ext: ['mf'], name: ['manifest'] },
  'maven': { name: ['mvnw', 'mvnw.cmd', 'mvnw.sh', 'pom.xml'] },
  'md': { ext: ['mdx', 'rst'], langId: ['markdown'] },
  'node': { name: ['package.json'] },
  'npm': { ext: ['npmignore'], name: ['package-lock.json'] },
  'objective-c': { langId: ['objective-c'] },
  'objective-cpp': { langId: ['objective-cpp'] },
  'perl': { langId: ['perl', 'raku'] },
  'php': { langId: ['php'] },
  'pnpm': { name: ['pnpm-lock.yaml', 'pnpm-workspace.yaml'] },
  'powershell': { langId: ['bat', 'powershell'] },
  'presentation': {
    ext: ['key', 'odp', 'otp', 'pot', 'potx', 'pps', 'ppsx', 'ppt', 'pptx'],
  },
  'prisma': { ext: ['prisma'], langId: ['prisma'] },
  'properties': { langId: ['properties', 'java-properties'] },
  'python': {
    name: [
      'pipfile',
      'pipfile.lock',
      'poetry.lock',
      'pyproject.toml',
      'requirements.txt',
    ],
    langId: ['python', 'jinja', 'pip-requirements'],
  },
  'react-js-config': { ext: ['config.jsx'] },
  'react-js-test': { ext: ['jest.jsx', 'spec.jsx', 'test.jsx'] },
  'react-js': { langId: ['javascriptreact'] },
  'react-ts-config': { ext: ['config.tsx'] },
  'react-ts-test': { ext: ['jest.tsx', 'spec.tsx', 'test.tsx'] },
  'react-ts': { langId: ['typescriptreact'] },
  'readme': { name: ['readme', 'readme.md', 'readme.txt'] },
  'ruby': { langId: ['ruby'] },
  'rust': { langId: ['rust'] },
  'scss': { langId: ['scss'] },
  'shell': {
    name: ['fish_plugins', 'fish_variables'],
    langId: ['shellscript'],
  },
  'sln': { ext: ['sln'] },
  'sql': { ext: ['db', 'sqlite'], langId: ['sql'] },
  'svg': { ext: ['svg', 'ai', 'eps', 'cdr', 'wmf', 'dxf'], langId: ['svg'] },
  'swift': { langId: ['swift'] },
  'table': {
    ext: [
      'csv',
      'gsheet',
      'numbers',
      'ods',
      'ots',
      'xls',
      'xlsb',
      'xlsm',
      'xlsx',
      'xltm',
      'xltx',
    ],
  },
  'text': { langId: ['plaintext'] },
  'toml': { ext: ['toml'], langId: ['toml'] },
  'tool': {
    ext: [
      'dotnet-version',
      'go-version',
      'java-version',
      'nvmrc',
      'php-version',
      'python-version',
      'ruby-gemset',
      'ruby-version',
      'rvmrc',
      'sdkmanrc',
      'tool-versions',
    ],
    name: ['mise.toml', 'mise.dev.toml', 'mise.prod.toml'],
  },
  'ts-config': { ext: ['config.ts', 'config.cts', 'config.mts'] },
  'ts-def': { ext: ['d.ts', 'd.cts', 'd.mts', 'def.ts', 'def.cts', 'def.mts'] },
  'ts-test': {
    ext: [
      'jest.ts',
      'jest.cts',
      'jest.mts',
      'spec.ts',
      'spec.cts',
      'spec.mts',
      'test.ts',
      'test.cts',
      'test.mts',
    ],
  },
  'ts': { langId: ['typescript'] },
  'tsconfig': {
    ext: ['tsbuildinfo'],
    name: [
      'tsconfig.json',
      'tsconfig.app.json',
      'tsconfig.spec.json',
      'tsconfig.node.json',
      'tsconfig.build.json',
    ],
  },
  'video': {
    ext: [
      'avi',
      'flv',
      'm4v',
      'mkv',
      'mov',
      'mp4',
      'mpeg',
      'mpg',
      'webm',
      'wmv',
    ],
  },
  'visual-basic': { langId: ['vb'] },
  'vscode': {
    ext: ['vscodeignore', 'code-workspace'],
    name: [
      '.vscode/settings.json',
      '.vscode/tasks.json',
      '.vscode/launch.json',
      '.vscode/keybindings.json',
      '.vscode/extensions.json',
    ],
    langId: ['snippets'],
  },
  'vue': { ext: ['vue'] },
  'web-assembly': { langId: ['wat'] },
  'xml': { langId: ['xml', 'xsl'] },
  'yaml': { langId: ['yaml'] },
  'yarn': { name: ['yarn.lock'] },
};
