import { splitFilesData } from './utils/split-files-data.js';
import { filePathGenerator } from './utils/file-path-generator.js';
import { generateRealObject } from './utils/generate-real-object.js';

const filesTemplates = {
  'audio': { ext: ['mp3', 'ogg', 'wav'], name: [], languageID: [] },
  'changelog': {
    ext: [],
    name: ['changelog', 'changelog.md', 'changelog.txt'],
    languageID: [],
  },
  'compact': {
    ext: [
      '7z',
      'AppImage',
      'aur',
      'bz2',
      'deb',
      'ear',
      'exe',
      'flatpak',
      'gz',
      'iso',
      'jar',
      'obs',
      'pkg',
      'ppa',
      'rar',
      'rpm',
      'snap',
      'tar',
      'tgz',
      'vsix',
      'war',
      'xz',
      'zip',
      'zst',
    ],
    name: [],
    languageID: [],
  },
  'config': {
    ext: ['cfg', 'config', 'editorconfig', 'ini', 'lock'],
    name: [],
    languageID: ['ini', 'makefile', 'ignore'],
  },
  'cs': { ext: ['cs'], name: [], languageID: ['csharp'] },
  'csproj': { ext: ['csproj'], name: [], languageID: [] },
  'css': { ext: [], name: [], languageID: ['css'] },
  'dart': { ext: [], name: [], languageID: ['dart'] },
  'diagram': {
    ext: ['drawio.png', 'drawio.svg', 'uml'],
    name: [],
    languageID: ['drawio'],
  },
  'docker-compose': { ext: [], name: [], languageID: ['dockercompose'] },
  'docker-ignore': { ext: ['dockerignore'], name: [], languageID: [] },
  'docker': { ext: [], name: [], languageID: ['dockerfile'] },
  'document': {
    ext: [
      'doc',
      'docm',
      'docx',
      'dot',
      'dotm',
      'dotx',
      'gdoc',
      'odt',
      'ott',
      'pages',
    ],
    name: [],
    languageID: [],
  },
  'env': { ext: ['venv'], name: [], languageID: ['dotenv'] },
  'flutter': { ext: ['flutter-plugins', 'packages'], name: [], languageID: [] },
  'git': {
    ext: ['gitignore', 'gitattributes', 'gitkeep'],
    name: [],
    languageID: ['git-commit', 'git-rebase'],
  },
  'gradle': {
    ext: ['gradle'],
    name: ['gradlew', 'gradlew.bat', 'gradlew.sh'],
    languageID: [],
  },
  'html': { ext: [], name: [], languageID: ['html'] },
  'http': {
    ext: ['bru', 'http', 'rc', 'rest', 'web'],
    name: [],
    languageID: [],
  },
  'icon': { ext: [], name: [], languageID: [] },
  'image': {
    ext: [
      'avif',
      'bmp',
      'gif',
      'heic',
      'heif',
      'icns',
      'ico',
      'jpeg',
      'jpg',
      'png',
      'tiff',
      'webp',
    ],
    name: [],
    languageID: [],
  },
  'java-class': { ext: ['class', 'jmod'], name: [], languageID: [] },
  'java': { ext: ['java', 'jsp'], name: [], languageID: ['java'] },
  'js-config': {
    ext: ['config.js', 'config.cjs', 'config.mjs'],
    name: [],
    languageID: [],
  },
  'js-map': { ext: ['js.map', 'cjs.map', 'mjs.map'], name: [], languageID: [] },
  'js-test': {
    ext: [
      'jest.js',
      'jest.cjs',
      'jest.mjs',
      'spec.js',
      'spec.cjs',
      'spec.mjs',
      'test.js',
      'test.cjs',
      'test.mjs',
    ],
    name: [],
    languageID: [],
  },
  'js': { ext: [], name: [], languageID: ['javascript'] },
  'jsconfig': {
    ext: [],
    name: ['jsconfig.json'],
    languageID: [],
  },
  'json': { ext: ['map'], name: [], languageID: ['json', 'jsonc', 'jsonl'] },
  'license': {
    ext: [],
    name: ['license', 'license.md', 'license.txt'],
    languageID: [],
  },
  'manifest': { ext: ['mf'], name: ['manifest'], languageID: [] },
  'maven': {
    ext: [],
    name: ['mvnw', 'mvnw.cmd', 'mvnw.sh', 'pom.xml'],
    languageID: [],
  },
  'md': { ext: ['mdx', 'rst'], name: [], languageID: ['markdown'] },
  'node': { ext: [], name: ['package.json'], languageID: [] },
  'npm': { ext: ['npmignore'], name: ['package-lock.json'], languageID: [] },
  'php': { ext: [], name: [], languageID: ['php'] },
  'pnpm': {
    ext: [],
    name: ['pnpm-lock.yaml', 'pnpm-workspace.yaml'],
    languageID: [],
  },
  'powershell': { ext: [], name: [], languageID: ['bat', 'powershell'] },
  'presentation': {
    ext: ['key', 'odp', 'otp', 'pot', 'potx', 'pps', 'ppsx', 'ppt', 'pptx'],
    name: [],
    languageID: [],
  },
  'prisma': { ext: ['prisma'], name: [], languageID: ['prisma'] },
  'properties': { ext: [], name: [], languageID: ['properties'] },
  'python': {
    ext: [],
    name: [
      'pipfile',
      'pipfile.lock',
      'poetry.lock',
      'pyproject.toml',
      'requirements.txt',
    ],
    languageID: ['python'],
  },
  'react-js-config': { ext: ['config.jsx'], name: [], languageID: [] },
  'react-js-test': {
    ext: ['jest.jsx', 'spec.jsx', 'test.jsx'],
    name: [],
    languageID: [],
  },
  'react-js': { ext: [], name: [], languageID: ['javascriptreact'] },
  'react-ts-config': { ext: ['config.tsx'], name: [], languageID: [] },
  'react-ts-test': {
    ext: ['jest.tsx', 'spec.tsx', 'test.tsx'],
    name: [],
    languageID: [],
  },
  'react-ts': { ext: [], name: [], languageID: ['typescriptreact'] },
  'readme': {
    ext: [],
    name: ['readme', 'readme.md', 'readme.txt'],
    languageID: [],
  },
  'scss': { ext: [], name: [], languageID: ['scss'] },
  'shell': { ext: [], name: [], languageID: ['shellscript'] },
  'sln': { ext: ['sln'], name: [], languageID: [] },
  'sql': { ext: ['db', 'sqlite'], name: [], languageID: ['sql'] },
  'svg': {
    ext: ['svg', 'ai', 'eps', 'cdr', 'wmf', 'dxf'],
    name: [],
    languageID: [],
  },
  'table': {
    ext: [
      'csv',
      'gsheet',
      'numbers',
      'ods',
      'ots',
      'xls',
      'xlsb',
      'xlsm',
      'xlsx',
      'xltm',
      'xltx',
    ],
    name: [],
    languageID: [],
  },
  'text': { ext: [], name: [], languageID: ['plaintext'] },
  'toml': { ext: [], name: [], languageID: ['toml'] },
  'tool': {
    ext: [
      'dotnet-version',
      'go-version',
      'java-version',
      'nvmrc',
      'php-version',
      'python-version',
      'ruby-gemset',
      'ruby-version',
      'rvmrc',
      'sdkmanrc',
      'tool-versions',
    ],
    name: [],
    languageID: [],
  },
  'ts-config': {
    ext: ['config.ts', 'config.cts', 'config.mts'],
    name: [],
    languageID: [],
  },
  'ts-def': {
    ext: ['d.ts', 'd.cts', 'd.mts', 'def.ts', 'def.cts', 'def.mts'],
    name: [],
    languageID: [],
  },
  'ts-test': {
    ext: [
      'jest.ts',
      'jest.cts',
      'jest.mts',
      'spec.ts',
      'spec.cts',
      'spec.mts',
      'test.ts',
      'test.cts',
      'test.mts',
    ],
    name: [],
    languageID: [],
  },
  'ts': { ext: [], name: [], languageID: ['typescript'] },
  'tsconfig': { ext: ['tsbuildinfo'], name: ['tsconfig.json'], languageID: [] },
  'video': {
    ext: [
      'avi',
      'flv',
      'm4v',
      'mkv',
      'mov',
      'mp4',
      'mpeg',
      'mpg',
      'webm',
      'wmv',
    ],
    name: [],
    languageID: [],
  },
  'vscode': {
    ext: ['vscodeignore', 'code-workspace'],
    name: [
      '.vscode/settings.json',
      '.vscode/tasks.json',
      '.vscode/launch.json',
      '.vscode/keybindings.json',
      '.vscode/extensions.json',
    ],
    languageID: [],
  },
  'vue': { ext: ['vue'], name: [], languageID: [] },
  'xml': { ext: [], name: [], languageID: ['xml', 'xsl'] },
  'yaml': { ext: [], name: [], languageID: ['yaml'] },
};

const { fileExtensionsTemplate, fileNamesTemplate, languageIdsTemplate } =
  splitFilesData(filesTemplates);

const files = Object.keys(filesTemplates);

export const fileDefinition = filePathGenerator('file', files);

export const languageIds = generateRealObject(languageIdsTemplate, 'file');
export const fileNames = generateRealObject(fileNamesTemplate, 'file');
export const fileExtensions = generateRealObject(
  fileExtensionsTemplate,
  'file',
);
