import { generateRealObject } from './utils/generate-real-object.js';

const fileNamesTemplates = {
  audio: [],
  changelog: ['changelog', 'changelog.md', 'changelog.txt'],
  compact: [],
  config: [],
  cs: [],
  csproj: [],
  css: [],
  dart: [],
  diagram: [],
  'docker-compose': [],
  'docker-ignore': [],
  docker: [],
  document: [],
  env: [],
  flutter: [],
  git: [],
  gradle: ['gradlew', 'gradlew.bat', 'gradlew.sh'],
  html: [],
  http: [],
  image: [],
  'java-class': [],
  java: [],
  'js-config': [],
  'js-map': [],
  'js-test': [],
  js: [],
  jsconfig: ['jsconfig.json'],
  json: [],
  license: ['license', 'license.md', 'license.txt'],
  manifest: ['manifest'],
  maven: ['mvnw', 'mvnw.cmd', 'mvnw.sh', 'pom.xml'],
  md: [],
  node: ['package.json'],
  npm: ['package-lock.json'],
  pnpm: ['pnpm-lock.yaml', 'pnpm-workspace.yaml'],
  powershell: [],
  presentation: [],
  prisma: [],
  properties: [],
  python: [
    'pipfile',
    'pipfile.lock',
    'poetry.lock',
    'pyproject.toml',
    'requirements.txt',
  ],
  'react-js-config': [],
  'react-js-test': [],
  'react-js': [],
  'react-ts-config': [],
  'react-ts-test': [],
  'react-ts': [],
  readme: ['readme', 'readme.md', 'readme.txt'],
  scss: [],
  shell: [],
  sln: [],
  sql: [],
  svg: [],
  table: [],
  text: [],
  toml: [],
  tool: [],
  'ts-config': [],
  'ts-def': [],
  'ts-test': [],
  ts: [],
  tsconfig: ['tsconfig.json'],
  video: [],
  vscode: [
    '.vscode/settings.json',
    '.vscode/tasks.json',
    '.vscode/launch.json',
    '.vscode/keybindings.json',
    '.vscode/extensions.json',
  ],
  vue: [],
  xml: [],
  yaml: [],
};

export const fileNames = generateRealObject(fileNamesTemplates, 'file');
