import type { FolderDefinitions } from 'vsc-icon-maker';

export const folders: FolderDefinitions = {
  angular: ['angular'],
  app: ['app', 'application', 'main'],
  assets: ['asset'],
  audio: ['audio'],
  benchmark: ['benchmark', 'bench'],
  client: ['client', 'frontend'],
  cmd: [
    'cmd',
    'shell',
    'bash',
    'fish',
    'zsh',
    'cli',
    'ci',
    'workflow',
    'completions',
  ],
  common: ['common'],
  component: ['component'],
  config: ['config', 'configuration', 'husky', 'conf.d'],
  controller: ['controller', 'resource'],
  css: ['css', 'style'],
  database: [
    'database',
    'data',
    'db',
    'sql',
    'mysql',
    'postgres',
    'mssql',
    'sqlite',
  ],
  desktop: ['desktop'],
  diff: ['diff'],
  dist: [
    'dist',
    'out',
    'build',
    'bin',
    'target',
    'output',
    'binary',
    'next',
    'astro',
  ],
  docker: ['docker', 'kubernetes'],
  docs: ['doc', 'documentation', 'info'],
  env: ['env', 'venv'],
  error: ['error', 'exception'],
  file: ['file'],
  folder: ['folder'],
  font: ['font'],
  function: ['function'],
  git: ['git'],
  gradle: ['gradle'],
  hook: ['hook'],
  html: ['view', 'page', 'html', 'template'],
  image: ['image', 'icon', 'img', 'media'],
  interface: ['interface'],
  java: ['java'],
  javascript: ['javascript', 'js'],
  job: ['job'],
  lib: ['lib', 'library'],
  log: ['log'],
  maven: ['mvn', 'maven'],
  middleware: ['middleware'],
  migration: ['migration'],
  mobile: ['mobile'],
  model: ['model', 'bean', 'class', 'entity', 'object'],
  module: ['module', 'plugin', 'extension'],
  node: ['node_modules', 'node'],
  obsidian: ['obsidian'],
  package: ['package', 'pack'],
  prisma: ['prisma'],
  private: ['private'],
  python: ['python', 'pycache'],
  remote: ['remote', 'github', 'gitlab'],
  repository: ['repository', 'repo'],
  route: ['route'],
  sample: ['sample', 'example', 'preview'],
  schema: ['schema', 'schemas'],
  script: ['script'],
  seed: ['seed', 'mongo', 'mongodb'],
  server: ['api', 'server', 'backend'],
  service: ['service', 'provider'],
  shared: ['share', 'shared'],
  src: ['src', 'code'],
  start: ['start', 'init', 'entrypoint'],
  temp: ['temp', 'tmp', 'cache'],
  test: ['test', 'spec', 'jest'],
  themes: ['theme', 'layout'],
  type: ['type', '@type', 'decorator', 'def', 'definition'],
  util: ['util'],
  vector: ['vector', 'svg'],
  video: ['video'],
  vscode: ['vscode', 'vscodium'],
  web: [
    'web',
    'www',
    'http',
    'request',
    'response',
    'rest',
    'graphql',
    'public',
    'static',
  ],
};
