import type { FolderDefinitions } from 'vsc-icon-maker';

export const folders: FolderDefinitions = {
  angular: ['angular'],
  app: ['app', 'application', 'main'],
  assets: ['asset'],
  audio: ['audio'],
  client: ['client', 'frontend'],
  cmd: ['cmd', 'shell', 'bash', 'fish', 'zsh', 'cli', 'ci', 'workflow'],
  component: ['component'],
  config: ['config', 'configuration'],
  controller: ['controller', 'resource'],
  css: ['css', 'style'],
  database: [
    'database',
    'data',
    'db',
    'sql',
    'mysql',
    'postgres',
    'mssql',
    'sqlite',
  ],
  diff: ['diff'],
  dist: ['dist', 'out', 'build', 'bin', 'target', 'output'],
  docs: ['doc', 'documentation', 'info'],
  env: ['env', 'venv'],
  error: ['error', 'exception'],
  file: ['file'],
  folder: ['folder'],
  font: ['font'],
  function: ['function'],
  git: ['git'],
  hook: ['hook'],
  html: ['view', 'page', 'html', 'template'],
  image: ['image', 'icon', 'img', 'media'],
  interface: ['interface'],
  java: ['java'],
  javascript: ['javascript', 'js'],
  job: ['job'],
  lib: ['lib'],
  log: ['log'],
  maven: ['mvn', 'maven'],
  middleware: ['middleware'],
  migration: ['migration'],
  mobile: ['mobile'],
  model: ['model', 'bean', 'class', 'entity', 'object'],
  module: ['module', 'plugin'],
  node: ['node_modules', 'node'],
  obsidian: ['obsidian'],
  package: ['package', 'pack'],
  prisma: ['prisma'],
  python: ['python', 'pycache'],
  repository: ['repository', 'repo'],
  route: ['route'],
  schema: ['schema', 'schemas'],
  script: ['script'],
  seed: ['seed', 'mongo', 'mongodb'],
  server: ['api', 'server', 'backend'],
  service: ['service', 'provider'],
  shared: ['share', 'shared'],
  src: ['src', 'code'],
  start: ['start', 'init'],
  temp: ['temp', 'tmp', 'cache'],
  test: ['test', 'spec', 'jest'],
  themes: ['theme'],
  type: ['type', '@type'],
  util: ['util'],
  vector: ['vector', 'svg'],
  video: ['video'],
  vscode: ['vscode'],
  web: [
    'web',
    'www',
    'http',
    'request',
    'response',
    'rest',
    'graphql',
    'public',
    'static',
  ],
};
