import type { FolderDefinitions } from 'vsc-icon-maker';

export const folders: FolderDefinitions = {
  angular: ['angular'],
  app: ['app', 'main'],
  assets: ['asset'],
  component: ['component'],
  config: ['config', 'configuration'],
  controller: ['controller', 'resource'],
  css: ['css', 'style'],
  database: ['database', 'data', 'db'],
  dist: ['dist', 'out', 'build', 'bin', 'target'],
  docs: ['doc', 'documentation'],
  error: ['error', 'exception'],
  file: ['file'],
  folder: ['folder'],
  font: ['font'],
  function: ['function'],
  git: ['git'],
  html: ['view', 'page', 'html', 'template'],
  image: ['image', 'icon', 'img'],
  interface: ['interface'],
  java: ['java'],
  javascript: ['javascript', 'js'],
  job: ['job'],
  lib: ['lib'],
  maven: ['mvn', 'maven'],
  migration: ['migration'],
  model: ['model', 'bean', 'class', 'entity'],
  module: ['module'],
  node_modules: ['node_modules'],
  obsidian: ['obsidian'],
  package: ['package'],
  prisma: ['prisma'],
  repository: ['repository'],
  route: ['route'],
  schema: ['schema', 'schemas'],
  script: ['script'],
  seed: ['seed'],
  server: ['api', 'server', 'backend'],
  service: ['service', 'provider'],
  shared: ['share', 'shared'],
  src: ['src'],
  test: ['test', 'spec', 'jest'],
  themes: ['theme'],
  type: ['type'],
  util: ['util'],
  vector: ['vector', 'svg'],
  vscode: ['vscode'],
};
