name: Publish on VSCode Marketplace and Open VSX Registry

on:
  push:
    branches:
      - main
    paths:
      - package.json

  workflow_dispatch:

jobs:
  publish:
    name: Publish Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: pnpm install

      - name: Generate the json file
        run: pnpm run build

      - name: Publish to Visual Studio Marketplace
        run: pnpm exec vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish to Open VSX Registry
        run: pnpm exec ovsx publish -p ${{ secrets.OVSX_TOKEN }}
